/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewAttemptIdRouteImport } from './routes/review.$attemptId'
import { Route as ResultsAttemptIdRouteImport } from './routes/results.$attemptId'
import { Route as QuizCategoryIdRouteImport } from './routes/quiz.$categoryId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewAttemptIdRoute = ReviewAttemptIdRouteImport.update({
  id: '/review/$attemptId',
  path: '/review/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsAttemptIdRoute = ResultsAttemptIdRouteImport.update({
  id: '/results/$attemptId',
  path: '/results/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCategoryIdRoute = QuizCategoryIdRouteImport.update({
  id: '/quiz/$categoryId',
  path: '/quiz/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/quiz/$categoryId': typeof QuizCategoryIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/review/$attemptId': typeof ReviewAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/quiz/$categoryId': typeof QuizCategoryIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/review/$attemptId': typeof ReviewAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/quiz/$categoryId': typeof QuizCategoryIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/review/$attemptId': typeof ReviewAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/quiz/$categoryId'
    | '/results/$attemptId'
    | '/review/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/quiz/$categoryId'
    | '/results/$attemptId'
    | '/review/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/quiz/$categoryId'
    | '/results/$attemptId'
    | '/review/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  QuizCategoryIdRoute: typeof QuizCategoryIdRoute
  ResultsAttemptIdRoute: typeof ResultsAttemptIdRoute
  ReviewAttemptIdRoute: typeof ReviewAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$attemptId': {
      id: '/review/$attemptId'
      path: '/review/$attemptId'
      fullPath: '/review/$attemptId'
      preLoaderRoute: typeof ReviewAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$attemptId': {
      id: '/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof ResultsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$categoryId': {
      id: '/quiz/$categoryId'
      path: '/quiz/$categoryId'
      fullPath: '/quiz/$categoryId'
      preLoaderRoute: typeof QuizCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  QuizCategoryIdRoute: QuizCategoryIdRoute,
  ResultsAttemptIdRoute: ResultsAttemptIdRoute,
  ReviewAttemptIdRoute: ReviewAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
